/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AiLyverRouteImport } from './routes/ai-lyver'
import { Route as IndexRouteImport } from './routes/index'

const AiLyverRoute = AiLyverRouteImport.update({
  id: '/ai-lyver',
  path: '/ai-lyver',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-lyver': typeof AiLyverRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-lyver': typeof AiLyverRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-lyver': typeof AiLyverRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ai-lyver'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ai-lyver'
  id: '__root__' | '/' | '/ai-lyver'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiLyverRoute: typeof AiLyverRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ai-lyver': {
      id: '/ai-lyver'
      path: '/ai-lyver'
      fullPath: '/ai-lyver'
      preLoaderRoute: typeof AiLyverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiLyverRoute: AiLyverRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
